window.VAPOR_PRODUCTS = [
    {
        id: 1,
        name: "Elf Bar BC5000",
        category: "disposable",
        brand: "Elf Bar",
        price: 12.99,
        originalPrice: 15.99,
        nicotine: "40mg",
        puffs: 5000,
        image: "resources/product-1.jpg",
        inStock: true,
        description: "Premium disposable vape with 5000 puffs and rich flavor selection",
        features: ["5000 Puffs", "40mg Nicotine", "Rechargeable", "Multiple Flavors"],
        popular: true,
        new: false
    },
    {
        id: 2,
        name: "Lost Mary OS5000",
        category: "disposable",
        brand: "Lost Mary",
        price: 14.99,
        originalPrice: 18.99,
        nicotine: "50mg",
        puffs: 5000,
        image: "resources/product-2.jpg",
        inStock: true,
        description: "Advanced disposable with exceptional flavor and smooth draw",
        features: ["5000 Puffs", "50mg Nicotine", "Mesh Coil", "Premium Flavors"],
        popular: true,
        new: true
    },
    {
        id: 3,
        name: "Geek Bar Pulse X",
        category: "disposable",
        brand: "Geek Bar",
        price: 16.99,
        originalPrice: 19.99,
        nicotine: "50mg",
        puffs: 25000,
        image: "resources/product-3.jpg",
        inStock: true,
        description: "High-capacity disposable with 25000 puffs and boost mode",
        features: ["25000 Puffs", "50mg Nicotine", "Boost Mode", "Full Screen"],
        popular: false,
        new: true
    },
    {
        id: 4,
        name: "Vaporesso XROS Pro",
        category: "kit",
        brand: "Vaporesso",
        price: 39.99,
        originalPrice: 49.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-4.jpg",
        inStock: true,
        description: "Premium pod system with adjustable airflow and OLED display",
        features: ["Adjustable Airflow", "OLED Display", "1200mAh Battery", "Top Fill"],
        popular: true,
        new: false
    },
    {
        id: 5,
        name: "Premium E-Liquid Collection",
        category: "liquid",
        brand: "Premium",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "3mg",
        puffs: null,
        image: "resources/product-5.jpg",
        inStock: true,
        description: "Three premium e-liquid flavors in 60ml bottles",
        features: ["3x 60ml Bottles", "3mg Nicotine", "High VG", "Premium Flavors"],
        popular: false,
        new: false
    },
    {
        id: 6,
        name: "Vape Coil & Accessory Kit",
        category: "accessory",
        brand: "Universal",
        price: 19.99,
        originalPrice: 24.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-6.jpg",
        inStock: true,
        description: "Complete accessory kit with coils, cotton, and tools",
        features: ["Multiple Coil Types", "Organic Cotton", "Cleaning Tools", "Carrying Case"],
        popular: false,
        new: false
    },
    {
        id: 7,
        name: "Luxury Pod System",
        category: "kit",
        brand: "Premium",
        price: 59.99,
        originalPrice: 79.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-7.jpg",
        inStock: true,
        description: "Luxury pod system with rose gold finish and premium features",
        features: ["Rose Gold Finish", "Premium Build", "Fast Charging", "Leak Proof"],
        popular: false,
        new: true
    },
    {
        id: 8,
        name: "Midnight Blue Disposable",
        category: "disposable",
        brand: "VooPoo",
        price: 13.99,
        originalPrice: 16.99,
        nicotine: "20mg",
        puffs: 3000,
        image: "resources/product-8.jpg",
        inStock: true,
        description: "Sleek disposable vape with midnight blue finish",
        features: ["3000 Puffs", "20mg Nicotine", "Compact Design", "Smooth Draw"],
        popular: false,
        new: false
    },
    {
        id: 9,
        name: "Vape Battery & Charger Set",
        category: "accessory",
        brand: "Universal",
        price: 29.99,
        originalPrice: 39.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-9.jpg",
        inStock: true,
        description: "High-capacity battery with USB-C fast charging",
        features: ["2000mAh Battery", "USB-C Charging", "LED Indicator", "Safety Protection"],
        popular: false,
        new: false
    },
    {
        id: 10,
        name: "Fruit Flavor E-Liquid Pack",
        category: "liquid",
        brand: "Fruit Master",
        price: 34.99,
        originalPrice: 42.99,
        nicotine: "6mg",
        puffs: null,
        image: "resources/product-10.jpg",
        inStock: true,
        description: "Collection of five premium fruit-flavored e-liquids",
        features: ["5x 30ml Bottles", "6mg Nicotine", "Natural Flavors", "High Quality"],
        popular: true,
        new: false
    },
    {
        id: 11,
        name: "Compact Pod Kit",
        category: "kit",
        brand: "Vaporesso",
        price: 34.99,
        originalPrice: 44.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-11.jpg",
        inStock: true,
        description: "Compact pod system perfect for beginners",
        features: ["Compact Size", "Easy to Use", "Good Battery Life", "Refillable Pods"],
        popular: false,
        new: false
    },
    {
        id: 12,
        name: "Tropical Disposable Vape",
        category: "disposable",
        brand: "Tropical",
        price: 11.99,
        originalPrice: 14.99,
        nicotine: "30mg",
        puffs: 2500,
        image: "resources/product-12.jpg",
        inStock: true,
        description: "Tropical-themed disposable with exotic flavors",
        features: ["2500 Puffs", "30mg Nicotine", "Tropical Flavors", "Gradient Design"],
        popular: false,
        new: true
    },
    {
        id: 13,
        name: "Advanced Box Mod",
        category: "kit",
        brand: "VooPoo",
        price: 79.99,
        originalPrice: 99.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-13.jpg",
        inStock: true,
        description: "Advanced box mod with temperature control and OLED display",
        features: ["200W Max Power", "Temperature Control", "OLED Display", "Dual Battery"],
        popular: true,
        new: false
    },
    {
        id: 14,
        name: "Nicotine Salt Collection",
        category: "liquid",
        brand: "Salt Nic",
        price: 27.99,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: null,
        image: "resources/product-14.jpg",
        inStock: true,
        description: "Three premium nicotine salt e-liquids in various flavors",
        features: ["3x 30ml Bottles", "20mg Nic Salts", "Smooth Hit", "Multiple Flavors"],
        popular: false,
        new: false
    },
    {
        id: 15,
        name: "Replacement Pod Pack",
        category: "accessory",
        brand: "Universal",
        price: 16.99,
        originalPrice: 21.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-15.jpg",
        inStock: true,
        description: "Pack of 4 replacement pods for various devices",
        features: ["4x Replacement Pods", "Multiple Resistances", "Easy to Install", "Long Lasting"],
        popular: false,
        new: false
    },
    {
        id: 16,
        name: "Mint Green Disposable",
        category: "disposable",
        brand: "Fresh",
        price: 10.99,
        originalPrice: 13.99,
        nicotine: "20mg",
        puffs: 2000,
        image: "resources/product-16.jpg",
        inStock: true,
        description: "Fresh mint green disposable with cooling menthol flavor",
        features: ["2000 Puffs", "20mg Nicotine", "Menthol Flavor", "Fresh Design"],
        popular: false,
        new: false
    },
    {
        id: 17,
        name: "Premium Vape Tank",
        category: "accessory",
        brand: "Premium",
        price: 44.99,
        originalPrice: 59.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-17.jpg",
        inStock: true,
        description: "High-quality vape tank with adjustable airflow",
        features: ["Adjustable Airflow", "Top Fill Design", "Sub-ohm Compatible", "Premium Build"],
        popular: false,
        new: true
    },
    {
        id: 18,
        name: "Starter Kit Package",
        category: "kit",
        brand: "Beginner",
        price: 49.99,
        originalPrice: 69.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-18.jpg",
        inStock: true,
        description: "Complete starter kit perfect for new vapers",
        features: ["Complete Kit", "Easy Setup", "Multiple Coils", "User Guide"],
        popular: true,
        new: false
    },
    {
        id: 19,
        name: "High-VG Cloud Collection",
        category: "liquid",
        brand: "Cloud Chaser",
        price: 39.99,
        originalPrice: 49.99,
        nicotine: "3mg",
        puffs: null,
        image: "resources/product-19.jpg",
        inStock: true,
        description: "Four high-VG e-liquids designed for massive clouds",
        features: ["4x 60ml Bottles", "3mg Nicotine", "80% VG", "Cloud Production"],
        popular: false,
        new: false
    },
    {
        id: 20,
        name: "Limited Edition Device",
        category: "kit",
        brand: "Limited",
        price: 99.99,
        originalPrice: 129.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-20.jpg",
        inStock: true,
        description: "Limited edition vape device with exclusive design",
        features: ["Limited Edition", "Exclusive Design", "Premium Materials", "Collector's Item"],
        popular: false,
        new: true
    },
    {
        id: 21,
        name: "Vape Accessory Kit",
        category: "accessory",
        brand: "Tool Master",
        price: 24.99,
        originalPrice: 32.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-21.jpg",
        inStock: true,
        description: "Essential accessories kit for vape maintenance",
        features: ["Cleaning Tools", "Replacement Parts", "Carrying Case", "User Manual"],
        popular: false,
        new: false
    },
    {
        id: 22,
        name: "Vaporesso Power Kit",
        category: "kit",
        brand: "Vaporesso",
        price: 89.99,
        originalPrice: 109.99,
        nicotine: "Variable",
        puffs: null,
        image: "IMG-20260325-WA0115-2.jpg",
        inStock: true,
        description: "High-performance Vaporesso kit with bold styling and advanced output control",
        features: ["Advanced Chipset", "Dual Power Mode", "Premium Tank", "Fast Charging"],
        popular: true,
        new: true
    },
    {
        id: 23,
        name: "VapSolo Triple Pro Blueberry Mango Cola",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.38.jpeg",
        inStock: true,
        description: "Bold fruit-forward Triple Pro blend with blueberry sour raspberry, strawberry mango, and lemon cola notes.",
        features: ["7000 Puffs", "20mg Nicotine", "Blueberry Sour Raspberry + Strawberry Mango + Lemon Cola", "Mesh Coil"],
        popular: true,
        new: true
    },
    {
        id: 24,
        name: "VapSolo Triple Pro Peach Dragon Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.39.jpeg",
        inStock: true,
        description: "Cooling fruit blend with peach ice, dragon fruit ice, and mixed fruit sweetness.",
        features: ["7000 Puffs", "20mg Nicotine", "Peach Ice + Dragon Fruit Ice + Mix Fruit", "Rechargeable"],
        popular: false,
        new: true
    },
    {
        id: 25,
        name: "VapSolo Triple Pro Berry Black Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.40.jpeg",
        inStock: true,
        description: "Ice-focused berry profile combining peach berry, black ice, and strawberry vanilla cola accents.",
        features: ["7000 Puffs", "20mg Nicotine", "Peach Berry + Black Ice + Strawberry Vanilla Cola", "Compact Body"],
        popular: false,
        new: true
    },
    {
        id: 26,
        name: "VapSolo Triple Pro Raspberry Mango Kiwi",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.41.jpeg",
        inStock: true,
        description: "Tropical-fruity combination featuring raspberry watermelon, mango peach, and strawberry kiwi.",
        features: ["7000 Puffs", "20mg Nicotine", "Raspberry Watermelon + Mango Peach + Strawberry Kiwi", "Mesh Coil"],
        popular: false,
        new: true
    },
    {
        id: 27,
        name: "VapSolo Triple Pro Cherry Cola Kiwi",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.42.jpeg",
        inStock: true,
        description: "Sweet and fresh Triple Pro profile with strawberry kiwi, Love 66 style notes, and cherry cola.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Kiwi + Love 66 + Cherry Cola", "Triple Flavor Core"],
        popular: false,
        new: true
    },
    {
        id: 28,
        name: "VapSolo Triple Pro Grape Mint Berry",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.43.jpeg",
        inStock: true,
        description: "Berry-mint focused mix built around strawberry raspberry, cherry berry, and grape mint.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Raspberry + Cherry Berry + Grape Mint", "Premium Flavor Blend"],
        popular: false,
        new: true
    },
    {
        id: 29,
        name: "VapSolo Triple Pro Watermelon Red Bull",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.44.jpeg",
        inStock: true,
        description: "Energy-inspired fruit profile with watermelon ice, red bull style notes, and strawberry kiwi.",
        features: ["7000 Puffs", "20mg Nicotine", "Watermelon Ice + Red Bull + Strawberry Kiwi", "Mesh Coil"],
        popular: true,
        new: true
    },
    {
        id: 30,
        name: "VapSolo Triple Pro Vanilla Berry Cola",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.45.jpeg",
        inStock: true,
        description: "Rich berry-cola profile combining strawberry vanilla coke, blueberry raspberry, and lemon lime.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Vanilla Coke + Blueberry Raspberry + Lemon Lime", "Rechargeable"],
        popular: false,
        new: true
    },
    {
        id: 31,
        name: "VapSolo Triple Pro Sour Mango Melon",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.46.jpeg",
        inStock: true,
        description: "Multi-fruit and sour profile featuring triple melon, sour mango, pineapple, and berry notes.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry + Raspberry + Triple Melon Sour Mango + Pineapple", "Triple Flavor Core"],
        popular: false,
        new: true
    },
    {
        id: 32,
        name: "VapSolo Triple Pro Citrus Blueberry Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.47.jpeg",
        inStock: true,
        description: "Refreshing citrus blend with lemon lime, strawberry, watermelon, and blueberry ice.",
        features: ["7000 Puffs", "20mg Nicotine", "Lemon Lime + Strawberry + Watermelon Blueberry Ice", "Mesh Coil"],
        popular: false,
        new: true
    },
    {
        id: 33,
        name: "VapSolo Triple Pro Gold Lemon Lime",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.49.jpeg",
        inStock: true,
        description: "Gold edition Triple Pro design with a lemon lime-forward profile and layered fruity freshness.",
        features: ["7000 Puffs", "20mg Nicotine", "Watermelon Ice + Red Bull + Strawberry Kiwi (Limited Art)", "Rechargeable"],
        popular: true,
        new: true
    }
];
