window.VAPOR_PRODUCTS = [
    {
        id: 1,
        name: "Elf Bar BC5000",
        category: "disposable",
        brand: "Elf Bar",
        price: 12.99,
        originalPrice: 15.99,
        nicotine: "40mg",
        puffs: 5000,
        image: "resources/product-1.jpg",
        inStock: true,
        description: "Premium disposable vape with 5000 puffs and rich flavor selection",
        features: ["5000 Puffs", "40mg Nicotine", "Rechargeable", "Multiple Flavors"],
        popular: true,
        new: false
    },
    {
        id: 2,
        name: "Lost Mary OS5000",
        category: "disposable",
        brand: "Lost Mary",
        price: 14.99,
        originalPrice: 18.99,
        nicotine: "50mg",
        puffs: 5000,
        image: "resources/product-2.jpg",
        inStock: true,
        description: "Advanced disposable with exceptional flavor and smooth draw",
        features: ["5000 Puffs", "50mg Nicotine", "Mesh Coil", "Premium Flavors"],
        popular: true,
        new: true
    },
    {
        id: 3,
        name: "Geek Bar Pulse X",
        category: "disposable",
        brand: "Geek Bar",
        price: 16.99,
        originalPrice: 19.99,
        nicotine: "50mg",
        puffs: 25000,
        image: "resources/product-3.jpg",
        inStock: true,
        description: "High-capacity disposable with 25000 puffs and boost mode",
        features: ["25000 Puffs", "50mg Nicotine", "Boost Mode", "Full Screen"],
        popular: false,
        new: true
    },
    {
        id: 4,
        name: "Vaporesso XROS Pro",
        category: "kit",
        brand: "Vaporesso",
        price: 39.99,
        originalPrice: 49.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-4.jpg",
        inStock: true,
        description: "Premium pod system with adjustable airflow and OLED display",
        features: ["Adjustable Airflow", "OLED Display", "1200mAh Battery", "Top Fill"],
        popular: true,
        new: false
    },
    {
        id: 5,
        name: "Premium E-Liquid Collection",
        category: "liquid",
        brand: "Premium",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "3mg",
        puffs: null,
        image: "resources/product-5.jpg",
        inStock: true,
        description: "Three premium e-liquid flavors in 60ml bottles",
        features: ["3x 60ml Bottles", "3mg Nicotine", "High VG", "Premium Flavors"],
        popular: false,
        new: false
    },
    {
        id: 6,
        name: "Vape Coil & Accessory Kit",
        category: "accessory",
        brand: "Universal",
        price: 19.99,
        originalPrice: 24.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-6.jpg",
        inStock: true,
        description: "Complete accessory kit with coils, cotton, and tools",
        features: ["Multiple Coil Types", "Organic Cotton", "Cleaning Tools", "Carrying Case"],
        popular: false,
        new: false
    },
    {
        id: 7,
        name: "Luxury Pod System",
        category: "kit",
        brand: "Premium",
        price: 59.99,
        originalPrice: 79.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-7.jpg",
        inStock: true,
        description: "Luxury pod system with rose gold finish and premium features",
        features: ["Rose Gold Finish", "Premium Build", "Fast Charging", "Leak Proof"],
        popular: false,
        new: true
    },
    {
        id: 8,
        name: "Midnight Blue Disposable",
        category: "disposable",
        brand: "VooPoo",
        price: 13.99,
        originalPrice: 16.99,
        nicotine: "20mg",
        puffs: 3000,
        image: "resources/product-8.jpg",
        inStock: true,
        description: "Sleek disposable vape with midnight blue finish",
        features: ["3000 Puffs", "20mg Nicotine", "Compact Design", "Smooth Draw"],
        popular: false,
        new: false
    },
    {
        id: 9,
        name: "Vape Battery & Charger Set",
        category: "accessory",
        brand: "Universal",
        price: 29.99,
        originalPrice: 39.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-9.jpg",
        inStock: true,
        description: "High-capacity battery with USB-C fast charging",
        features: ["2000mAh Battery", "USB-C Charging", "LED Indicator", "Safety Protection"],
        popular: false,
        new: false
    },
    {
        id: 10,
        name: "Fruit Flavor E-Liquid Pack",
        category: "liquid",
        brand: "Fruit Master",
        price: 34.99,
        originalPrice: 42.99,
        nicotine: "6mg",
        puffs: null,
        image: "resources/product-10.jpg",
        inStock: true,
        description: "Collection of five premium fruit-flavored e-liquids",
        features: ["5x 30ml Bottles", "6mg Nicotine", "Natural Flavors", "High Quality"],
        popular: true,
        new: false
    },
    {
        id: 11,
        name: "Compact Pod Kit",
        category: "kit",
        brand: "Vaporesso",
        price: 34.99,
        originalPrice: 44.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-11.jpg",
        inStock: true,
        description: "Compact pod system perfect for beginners",
        features: ["Compact Size", "Easy to Use", "Good Battery Life", "Refillable Pods"],
        popular: false,
        new: false
    },
    {
        id: 12,
        name: "Tropical Disposable Vape",
        category: "disposable",
        brand: "Tropical",
        price: 11.99,
        originalPrice: 14.99,
        nicotine: "30mg",
        puffs: 2500,
        image: "resources/product-12.jpg",
        inStock: true,
        description: "Tropical-themed disposable with exotic flavors",
        features: ["2500 Puffs", "30mg Nicotine", "Tropical Flavors", "Gradient Design"],
        popular: false,
        new: true
    },
    {
        id: 13,
        name: "Advanced Box Mod",
        category: "kit",
        brand: "VooPoo",
        price: 79.99,
        originalPrice: 99.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-13.jpg",
        inStock: true,
        description: "Advanced box mod with temperature control and OLED display",
        features: ["200W Max Power", "Temperature Control", "OLED Display", "Dual Battery"],
        popular: true,
        new: false
    },
    {
        id: 14,
        name: "Nicotine Salt Collection",
        category: "liquid",
        brand: "Salt Nic",
        price: 27.99,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: null,
        image: "resources/product-14.jpg",
        inStock: true,
        description: "Three premium nicotine salt e-liquids in various flavors",
        features: ["3x 30ml Bottles", "20mg Nic Salts", "Smooth Hit", "Multiple Flavors"],
        popular: false,
        new: false
    },
    {
        id: 15,
        name: "Replacement Pod Pack",
        category: "accessory",
        brand: "Universal",
        price: 16.99,
        originalPrice: 21.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-15.jpg",
        inStock: true,
        description: "Pack of 4 replacement pods for various devices",
        features: ["4x Replacement Pods", "Multiple Resistances", "Easy to Install", "Long Lasting"],
        popular: false,
        new: false
    },
    {
        id: 16,
        name: "Mint Green Disposable",
        category: "disposable",
        brand: "Fresh",
        price: 10.99,
        originalPrice: 13.99,
        nicotine: "20mg",
        puffs: 2000,
        image: "resources/product-16.jpg",
        inStock: true,
        description: "Fresh mint green disposable with cooling menthol flavor",
        features: ["2000 Puffs", "20mg Nicotine", "Menthol Flavor", "Fresh Design"],
        popular: false,
        new: false
    },
    {
        id: 17,
        name: "Premium Vape Tank",
        category: "accessory",
        brand: "Premium",
        price: 44.99,
        originalPrice: 59.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-17.jpg",
        inStock: true,
        description: "High-quality vape tank with adjustable airflow",
        features: ["Adjustable Airflow", "Top Fill Design", "Sub-ohm Compatible", "Premium Build"],
        popular: false,
        new: true
    },
    {
        id: 18,
        name: "Starter Kit Package",
        category: "kit",
        brand: "Beginner",
        price: 49.99,
        originalPrice: 69.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-18.jpg",
        inStock: true,
        description: "Complete starter kit perfect for new vapers",
        features: ["Complete Kit", "Easy Setup", "Multiple Coils", "User Guide"],
        popular: true,
        new: false
    },
    {
        id: 19,
        name: "High-VG Cloud Collection",
        category: "liquid",
        brand: "Cloud Chaser",
        price: 39.99,
        originalPrice: 49.99,
        nicotine: "3mg",
        puffs: null,
        image: "resources/product-19.jpg",
        inStock: true,
        description: "Four high-VG e-liquids designed for massive clouds",
        features: ["4x 60ml Bottles", "3mg Nicotine", "80% VG", "Cloud Production"],
        popular: false,
        new: false
    },
    {
        id: 20,
        name: "Limited Edition Device",
        category: "kit",
        brand: "Limited",
        price: 99.99,
        originalPrice: 129.99,
        nicotine: "Variable",
        puffs: null,
        image: "resources/product-20.jpg",
        inStock: true,
        description: "Limited edition vape device with exclusive design",
        features: ["Limited Edition", "Exclusive Design", "Premium Materials", "Collector's Item"],
        popular: false,
        new: true
    },
    {
        id: 21,
        name: "Vape Accessory Kit",
        category: "accessory",
        brand: "Tool Master",
        price: 24.99,
        originalPrice: 32.99,
        nicotine: "N/A",
        puffs: null,
        image: "resources/product-21.jpg",
        inStock: true,
        description: "Essential accessories kit for vape maintenance",
        features: ["Cleaning Tools", "Replacement Parts", "Carrying Case", "User Manual"],
        popular: false,
        new: false
    },
    {
        id: 22,
        name: "Vaporesso Power Kit",
        category: "kit",
        brand: "Vaporesso",
        price: 89.99,
        originalPrice: 109.99,
        nicotine: "Variable",
        puffs: null,
        image: "IMG-20260325-WA0115-2.jpg",
        inStock: true,
        description: "High-performance Vaporesso kit with bold styling and advanced output control",
        features: ["Advanced Chipset", "Dual Power Mode", "Premium Tank", "Fast Charging"],
        popular: true,
        new: true
    },
    {
        id: 23,
        name: "VapSolo Triple Pro Blueberry Mango Cola",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.38.jpeg",
        inStock: true,
        description: "Bold fruit-forward Triple Pro blend with blueberry sour raspberry, strawberry mango, and lemon cola notes.",
        features: ["7000 Puffs", "20mg Nicotine", "Blueberry Sour Raspberry + Strawberry Mango + Lemon Cola", "Mesh Coil"],
        popular: true,
        new: true
    },
    {
        id: 24,
        name: "VapSolo Triple Pro Peach Dragon Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.39.jpeg",
        inStock: true,
        description: "Cooling fruit blend with peach ice, dragon fruit ice, and mixed fruit sweetness.",
        features: ["7000 Puffs", "20mg Nicotine", "Peach Ice + Dragon Fruit Ice + Mix Fruit", "Rechargeable"],
        popular: false,
        new: true
    },
    {
        id: 25,
        name: "VapSolo Triple Pro Berry Black Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.40.jpeg",
        inStock: true,
        description: "Ice-focused berry profile combining peach berry, black ice, and strawberry vanilla cola accents.",
        features: ["7000 Puffs", "20mg Nicotine", "Peach Berry + Black Ice + Strawberry Vanilla Cola", "Compact Body"],
        popular: false,
        new: true
    },
    {
        id: 26,
        name: "VapSolo Triple Pro Raspberry Mango Kiwi",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.41.jpeg",
        inStock: true,
        description: "Tropical-fruity combination featuring raspberry watermelon, mango peach, and strawberry kiwi.",
        features: ["7000 Puffs", "20mg Nicotine", "Raspberry Watermelon + Mango Peach + Strawberry Kiwi", "Mesh Coil"],
        popular: false,
        new: true
    },
    {
        id: 27,
        name: "VapSolo Triple Pro Cherry Cola Kiwi",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.42.jpeg",
        inStock: true,
        description: "Sweet and fresh Triple Pro profile with strawberry kiwi, Love 66 style notes, and cherry cola.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Kiwi + Love 66 + Cherry Cola", "Triple Flavor Core"],
        popular: false,
        new: true
    },
    {
        id: 28,
        name: "VapSolo Triple Pro Grape Mint Berry",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.43.jpeg",
        inStock: true,
        description: "Berry-mint focused mix built around strawberry raspberry, cherry berry, and grape mint.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Raspberry + Cherry Berry + Grape Mint", "Premium Flavor Blend"],
        popular: false,
        new: true
    },
    {
        id: 29,
        name: "VapSolo Triple Pro Watermelon Red Bull",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.44.jpeg",
        inStock: true,
        description: "Energy-inspired fruit profile with watermelon ice, red bull style notes, and strawberry kiwi.",
        features: ["7000 Puffs", "20mg Nicotine", "Watermelon Ice + Red Bull + Strawberry Kiwi", "Mesh Coil"],
        popular: true,
        new: true
    },
    {
        id: 30,
        name: "VapSolo Triple Pro Vanilla Berry Cola",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.45.jpeg",
        inStock: true,
        description: "Rich berry-cola profile combining strawberry vanilla coke, blueberry raspberry, and lemon lime.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry Vanilla Coke + Blueberry Raspberry + Lemon Lime", "Rechargeable"],
        popular: false,
        new: true
    },
    {
        id: 31,
        name: "VapSolo Triple Pro Sour Mango Melon",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.46.jpeg",
        inStock: true,
        description: "Multi-fruit and sour profile featuring triple melon, sour mango, pineapple, and berry notes.",
        features: ["7000 Puffs", "20mg Nicotine", "Strawberry + Raspberry + Triple Melon Sour Mango + Pineapple", "Triple Flavor Core"],
        popular: false,
        new: true
    },
    {
        id: 32,
        name: "VapSolo Triple Pro Citrus Blueberry Ice",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.47.jpeg",
        inStock: true,
        description: "Refreshing citrus blend with lemon lime, strawberry, watermelon, and blueberry ice.",
        features: ["7000 Puffs", "20mg Nicotine", "Lemon Lime + Strawberry + Watermelon Blueberry Ice", "Mesh Coil"],
        popular: false,
        new: true
    },
    {
        id: 33,
        name: "VapSolo Triple Pro Gold Lemon Lime",
        category: "vapsolo",
        brand: "VapSolo",
        price: 28.98,
        originalPrice: 34.99,
        nicotine: "20mg",
        puffs: 7000,
        image: "solov/WhatsApp Image 2026-03-27 at 02.37.49.jpeg",
        inStock: true,
        description: "Gold edition Triple Pro design with a lemon lime-forward profile and layered fruity freshness.",
        features: ["7000 Puffs", "20mg Nicotine", "Watermelon Ice + Red Bull + Strawberry Kiwi (Limited Art)", "Rechargeable"],
        popular: true,
        new: true
    },
    {
        id: 34,
        name: "Vozol RAVE 40000 Blue Razz Ice",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-blue-razz-ice.jpg",
        inStock: true,
        description: "RAVE 40000 disposable in Blue Razz Ice. Regular mode up to 40,000 puffs, Surge mode up to 25,000. World's first 270° beat sensing display.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Blue Razz Ice"],
        popular: true,
        new: true
    },
    {
        id: 35,
        name: "Vozol RAVE 40000 Strawberry Ice",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-strawberry-ice.jpg",
        inStock: true,
        description: "Strawberry Ice profile with dual power modes and illuminated textured shell.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Strawberry Ice"],
        popular: false,
        new: true
    },
    {
        id: 36,
        name: "Vozol RAVE 40000 Double Apple",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-double-apple.jpg",
        inStock: true,
        description: "Double Apple flavor with neon lime-green finish and bubble texture lighting.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Double Apple"],
        popular: false,
        new: true
    },
    {
        id: 37,
        name: "Vozol RAVE 40000 Cherry Strawberry",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-cherry-strawberry.jpg",
        inStock: true,
        description: "Cherry Strawberry blend on a cyan body with glowing accent display.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Cherry Strawberry"],
        popular: false,
        new: true
    },
    {
        id: 38,
        name: "Vozol RAVE 40000 Blueberry Watermelon",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-blueberry-watermelon.jpg",
        inStock: true,
        description: "Blueberry Watermelon with deep blue shell and oval bubble illumination.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "Beat Sensing Display", "Blueberry Watermelon"],
        popular: false,
        new: true
    },
    {
        id: 39,
        name: "Vozol RAVE 40000 Watermelon Bubblegum",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-watermelon-bubblegum.jpg",
        inStock: true,
        description: "Watermelon Bubblegum with lime-green body and cyan glow accents.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Watermelon Bubblegum"],
        popular: false,
        new: true
    },
    {
        id: 40,
        name: "Vozol RAVE 40000 Strawberry Watermelon",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-strawberry-watermelon.jpg",
        inStock: true,
        description: "Strawberry Watermelon with pink and lime accents and mesh-style shell.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Strawberry Watermelon"],
        popular: true,
        new: true
    },
    {
        id: 41,
        name: "Vozol RAVE 40000 LOVE 777",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-love-777.jpg",
        inStock: true,
        description: "LOVE 777 edition with purple shell and multicolor beat display rings.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "LOVE 777"],
        popular: false,
        new: true
    },
    {
        id: 42,
        name: "Vozol RAVE 40000 Peach Raspberry Lemonade",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-peach-raspberry-lemonade.jpg",
        inStock: true,
        description: "Peach Raspberry Lemonade on a chrome-silver body with green accent lighting.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Peach Raspberry Lemonade"],
        popular: false,
        new: true
    },
    {
        id: 43,
        name: "Vozol RAVE 20000 Mango Ice",
        category: "vozol",
        brand: "Vozol",
        price: 18.99,
        originalPrice: 22.99,
        nicotine: "50mg",
        puffs: 20000,
        image: "vozol/rave-20000-mango-ice.jpg",
        inStock: true,
        description: "Compact RAVE 20000 line: Regular up to 20,000 puffs, Surge up to 14,000. Mango Ice with yellow shell.",
        features: ["20K / 14K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Mango Ice"],
        popular: false,
        new: true
    },
    {
        id: 44,
        name: "Vozol RAVE 40000 Watermelon Razz Rancher",
        category: "vozol",
        brand: "Vozol",
        price: 22.99,
        originalPrice: 27.99,
        nicotine: "50mg",
        puffs: 40000,
        image: "vozol/rave-40000-watermelon-razz-rancher.jpg",
        inStock: true,
        description: "Watermelon Razz Rancher with purple finish and pink–yellow illuminated windows.",
        features: ["40K / 25K dual modes", "50mg Nicotine", "Beat Sensing Display", "Watermelon Razz Rancher"],
        popular: false,
        new: true
    },
    {
        id: 45,
        name: "Vozol RAVE 50000 Strawberry Soft Pop",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-strawberry-soft-pop.jpg",
        inStock: true,
        description: "High-capacity RAVE 50000: Regular up to 50,000 puffs, Surge up to 35,000. Strawberry Soft Pop in hot pink.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "270° Beat Sensing Display", "Strawberry Soft Pop"],
        popular: true,
        new: true
    },
    {
        id: 46,
        name: "Crown Bar 8000 PRO Black Currant Mint",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-black-currant-mint.jpg",
        inStock: true,
        description: "Al Fakher Crown Bar 8000 PRO with dual ECO/BOOST modes, big screen for battery and e-liquid, Black Currant Mint.",
        features: ["8000 Puffs", "Dual Mode ECO/BOOST", "Big Screen Display", "Big Cloud"],
        popular: false,
        new: true
    },
    {
        id: 47,
        name: "Crown Bar 8000 PRO Grape Mint",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-grape-mint.jpg",
        inStock: true,
        description: "8000 PRO Grape Mint with textured purple body and full front display.",
        features: ["8000 Puffs", "Dual Mode", "Big Screen Display", "Grape Mint"],
        popular: false,
        new: true
    },
    {
        id: 48,
        name: "Crown Bar 8000 PRO Lush Ice",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-lush-ice.jpg",
        inStock: true,
        description: "Lush Ice variant with icy purple styling and smart battery/juice readouts.",
        features: ["8000 Puffs", "Dual Mode ECO/BOOST", "Big Screen", "Lush Ice"],
        popular: true,
        new: true
    },
    {
        id: 49,
        name: "Crown Bar 8000 PRO Gum Mint",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-gum-mint.jpg",
        inStock: true,
        description: "Gum Mint with turquoise textured grip and vertical status screen.",
        features: ["8000 Puffs", "Dual Mode", "Adjustable modes", "Gum Mint"],
        popular: false,
        new: true
    },
    {
        id: 50,
        name: "Crown Bar 8000 Crystal Strawberry Punch",
        category: "crownbar",
        brand: "Crown Bar",
        price: 23.99,
        originalPrice: 28.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-crystal-strawberry-punch.jpg",
        inStock: true,
        description: "8000 Crystal Dual Mode DTL-style device with strawberry punch profile and metallic bronze finish.",
        features: ["8000 Puffs", "Crystal Dual Mode", "DTL", "Strawberry Punch"],
        popular: true,
        new: true
    },
    {
        id: 51,
        name: "Crown Bar 8000 PRO Berry Ice",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-berry-ice.jpg",
        inStock: true,
        description: "Berry Ice with dark purple leather-look body and ice-themed box art.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Screen", "Berry Ice"],
        popular: false,
        new: true
    },
    {
        id: 52,
        name: "Crown Bar 8000 PRO Black Currant Ice",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-black-currant-ice.jpg",
        inStock: true,
        description: "Black Currant Ice with teal body and icy purple packaging accents.",
        features: ["8000 Puffs", "Dual Mode", "Big Cloud", "Black Currant Ice"],
        popular: false,
        new: true
    },
    {
        id: 53,
        name: "Crown Bar 8000 PRO Blue Razz Lemonade",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-blue-razz-lemonade.jpg",
        inStock: true,
        description: "Blue Razz Lemonade with olive-green textured shell and bold brushstroke box.",
        features: ["8000 Puffs", "Dual Mode", "Big Screen Display", "Blue Razz Lemonade"],
        popular: false,
        new: true
    },
    {
        id: 54,
        name: "Crown Bar 8000 PRO Magic Love",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-magic-love.jpg",
        inStock: true,
        description: "Magic Love in deep purple with premium leather-style texture.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Screen", "Magic Love"],
        popular: false,
        new: true
    },
    {
        id: 55,
        name: "Crown Bar 8000 PRO Lemon Mint",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-lemon-mint.jpg",
        inStock: true,
        description: "Lemon Mint with teal device and citrus brushstroke packaging.",
        features: ["8000 Puffs", "Dual Mode", "Big Cloud", "Lemon Mint"],
        popular: false,
        new: true
    },
    {
        id: 56,
        name: "Crown Bar 8000 PRO Lemon Lime",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-lemon-lime.jpg",
        inStock: true,
        description: "Lemon Lime with olive-green body and yellow-green box highlights.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Screen", "Lemon Lime"],
        popular: false,
        new: true
    },
    {
        id: 57,
        name: "Crown Bar 8000 PRO Blueberry Gum",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-blueberry-gum.jpg",
        inStock: true,
        description: "Blueberry Gum with dark purple finish and blue–purple gradient box.",
        features: ["8000 Puffs", "Dual Mode", "2 Adjustable Modes", "Blueberry Gum"],
        popular: false,
        new: true
    },
    {
        id: 58,
        name: "Crown Bar 8000 PRO Mango Pineapple",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-mango-pineapple.jpg",
        inStock: true,
        description: "Mango Pineapple with vibrant orange leather-textured body.",
        features: ["8000 Puffs", "Dual Mode", "Big Screen", "Mango Pineapple"],
        popular: true,
        new: true
    },
    {
        id: 59,
        name: "Crown Bar 8000 PRO Space Dream",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-space-dream.jpg",
        inStock: true,
        description: "Space Dream with olive-green shell and cosmic-themed accents.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Cloud", "Space Dream"],
        popular: false,
        new: true
    },
    {
        id: 60,
        name: "Crown Bar 8000 PRO Berry Blue",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-berry-blue.jpg",
        inStock: true,
        description: "Berry Blue with turquoise textured finish and crown branding.",
        features: ["8000 Puffs", "Dual Mode", "Big Screen", "Berry Blue"],
        popular: false,
        new: true
    },
    {
        id: 61,
        name: "Crown Bar 8000 PRO Peach Ice",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-peach-ice.jpg",
        inStock: true,
        description: "Peach Ice with orange body and frosty box graphics.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Cloud", "Peach Ice"],
        popular: false,
        new: true
    },
    {
        id: 62,
        name: "Crown Bar 8000 PRO Cool Mango",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-cool-mango.jpg",
        inStock: true,
        description: "Cool Mango with golden honey-yellow leather finish.",
        features: ["8000 Puffs", "Dual Mode", "Big Screen", "Cool Mango"],
        popular: false,
        new: true
    },
    {
        id: 63,
        name: "Crown Bar 8000 PRO Hubba",
        category: "crownbar",
        brand: "Crown Bar",
        price: 24.99,
        originalPrice: 29.99,
        nicotine: "50mg",
        puffs: 8000,
        image: "crownbar/8000-pro-hubba.jpg",
        inStock: true,
        description: "Hubba bubblegum-inspired profile with deep purple body and lime-yellow box art.",
        features: ["8000 Puffs", "ECO/BOOST", "Big Screen", "Hubba"],
        popular: false,
        new: true
    },
    {
        id: 64,
        name: "Vozol RAVE 50000 Strawberry Banana",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-strawberry-banana.jpg",
        inStock: true,
        description: "RAVE 50000 Strawberry Banana. Regular up to 50,000 puffs, Surge up to 35,000. Dual firing modes and beat sensing display.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Strawberry Banana"],
        popular: false,
        new: true
    },
    {
        id: 65,
        name: "Vozol RAVE 50000 Watermelon Razz Rancher",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-watermelon-razz-rancher.jpg",
        inStock: true,
        description: "RAVE 50000 Watermelon Razz Rancher. High-capacity disposable with 50K regular / 35K surge mode.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Watermelon Razz Rancher"],
        popular: false,
        new: true
    },
    {
        id: 66,
        name: "Vozol RAVE 50000 Watermelon Ice",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-watermelon-ice.jpg",
        inStock: true,
        description: "RAVE 50000 Watermelon Ice with icy fruit profile and extended puff counts.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Watermelon Ice"],
        popular: false,
        new: true
    },
    {
        id: 67,
        name: "Vozol RAVE 50000 Blue Razz Ice",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-blue-razz-ice.jpg",
        inStock: true,
        description: "RAVE 50000 Blue Razz Ice — cool blue raspberry with dual power modes.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Blue Razz Ice"],
        popular: true,
        new: true
    },
    {
        id: 68,
        name: "Vozol RAVE 50000 Peach Ice",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-peach-ice.jpg",
        inStock: true,
        description: "RAVE 50000 Peach Ice with sweet peach and cooling finish.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Peach Ice"],
        popular: false,
        new: true
    },
    {
        id: 69,
        name: "Vozol RAVE 50000 Blue Mint",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-blue-mint.jpg",
        inStock: true,
        description: "RAVE 50000 Blue Mint — crisp mint with blue fruit notes.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Blue Mint"],
        popular: false,
        new: true
    },
    {
        id: 70,
        name: "Vozol RAVE 50000 Strawberry Kiwi",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-strawberry-kiwi.jpg",
        inStock: true,
        description: "RAVE 50000 Strawberry Kiwi — classic berry pairing with max puff capacity.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Strawberry Kiwi"],
        popular: false,
        new: true
    },
    {
        id: 71,
        name: "Vozol RAVE 50000 Miami Mint",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-miami-mint.jpg",
        inStock: true,
        description: "RAVE 50000 Miami Mint with fresh mint and citrus-style chill.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Miami Mint"],
        popular: false,
        new: true
    },
    {
        id: 72,
        name: "Vozol RAVE 50000 Hawaiian Pineapple Paradise",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-hawaiian-pineapple-paradise.jpg",
        inStock: true,
        description: "RAVE 50000 Hawaiian Pineapple Paradise — tropical pineapple blend.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Hawaiian Pineapple Paradise"],
        popular: false,
        new: true
    },
    {
        id: 73,
        name: "Vozol RAVE 50000 Blueberry Watermelon",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-blueberry-watermelon.jpg",
        inStock: true,
        description: "RAVE 50000 Blueberry Watermelon — mixed berry and melon profile.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Blueberry Watermelon"],
        popular: false,
        new: true
    },
    {
        id: 74,
        name: "Vozol RAVE 50000 Grape Ice",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-grape-ice.jpg",
        inStock: true,
        description: "RAVE 50000 Grape Ice with bold grape and icy exhale.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Grape Ice"],
        popular: false,
        new: true
    },
    {
        id: 75,
        name: "Vozol RAVE 50000 Banana Taffy",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-banana-taffy.jpg",
        inStock: true,
        description: "RAVE 50000 Banana Taffy — creamy banana candy style notes.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Banana Taffy"],
        popular: false,
        new: true
    },
    {
        id: 76,
        name: "Vozol RAVE 50000 Lemon Heads",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-lemon-heads.jpg",
        inStock: true,
        description: "RAVE 50000 Lemon Heads — sour lemon candy inspired profile.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Lemon Heads"],
        popular: false,
        new: true
    },
    {
        id: 77,
        name: "Vozol RAVE 50000 Sour Apple Ice",
        category: "vozol",
        brand: "Vozol",
        price: 29.99,
        originalPrice: 34.99,
        nicotine: "50mg",
        puffs: 50000,
        image: "vozol/rave-50000-sour-apple-ice.jpg",
        inStock: true,
        description: "RAVE 50000 Sour Apple Ice — tart green apple with cooling finish.",
        features: ["50K / 35K dual modes", "50mg Nicotine", "Beat Sensing Display", "Sour Apple Ice"],
        popular: false,
        new: true
    }
];
